---
# tasks file for master
        - name: Install Docker
          package:
               name: "docker"
               state: present

        - name: Start and Enabled the Docker Service
          service:
               name: "docker"
               state: started
               enabled: yes

        - name: Configuring K8s Repository
          shell: |
                 cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
                 [kubernetes]
                 name=Kubernetes
                 baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                 enabled=1
                 gpgcheck=1
                 repo_gpgcheck=1
                 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                 exclude=kubelet kubeadm kubectl
                 
        - name: Install Kubelet Kubeadm and Kubectl
          command: "yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"
          
        - name: Enable Kubelet Services
          service: 
               name: "kubelet"
               state: started
               enabled: yes

        - name: Pull Kubeadm Config Images
          command: "kubeadm config images pull"

        - name: Copying Daemon.json file
          copy:
             dest: /etc/docker/daemon.json
             src: daemon.json

        - name: Restart Docker Services
          service:
                  name: "docker"
                  state: restarted

        - name: Install iproute-tc Package 
          package:
                  name: "iproute-tc"
                  state: present

        - name: K8s.conf File
          shell: |     
                   cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
                   net.bridge.bridge-nf-call-ip6tables = 1
                   net.bridge.bridge-nf-call-iptables = 1
                   
        - name: Restart sysctl
          command: "sysctl --system"

        - name: Initialize Pod Network CIDR Range
          command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"

        - name: Create a Parent Directory and its Sub-Directory
          file: 
              name:  "$HOME/.kube"
              state: directory

        - name: Copying config file
          command: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

        - name: Change the user ownership of config file
          shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

        - name: Installing Flannel
          command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

        - name: Create Join Command
          command: "kubeadm token create --print-join-command"
          register: Join
      
        - name: Print the output
          local_action: copy content={{ Join.stdout }} dest=/root/k8/token
